name: islamic_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:

  sdk: '>=3.0.0 <3.5.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_animate: ^4.1.1+1
  awesome_dialog: ^3.1.1
  intl: ^0.19.0
  font_awesome_icon_class: ^0.0.6
  hijri: ^3.0.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.5
  adhan: ^2.0.0+1
  google_fonts: ^6.1.0
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0 
  audioplayers: ^6.4.0
  permission_handler: ^11.3.1
  dio: ^5.4.0
  device_info_plus: ^9.0.0
  shared_preferences: 2.3.3
  flutter_compass: ^0.8.1
  geolocator: ^13.0.2
  geocoding: ^4.0.0
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.jpg" # replace with your actual icon path

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/gmail.png
    - assets/Quran.JSON
    - assets/Azkar.JSON
    - assets/Ahadith.JSON
    - assets/Surah.JSON
    - assets/location.png
    - assets/ic_launcher.jpg
    - assets/background.jpg
    - assets/ayah.jpg
    - assets/prayer.jpg
    - assets/zekr_background.jpg
    - assets/compass.jpg
    - assets/kaaba_icon.png
    - assets/border.jpeg

  # fonts:
  #   - family: lateef
  #     fonts:
  #       - asset: assets/Lateef-Bold.ttf
